accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

app_name = 'accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('registerapp.urls')),
    path('account/', include('accountapp.urls')),
]

registerapp/urls.py
from django.urls import path
from .views import upload_files, homepage, search_scenarios, check_duplicate

app_name = 'registerapp'

urlpatterns = [
    path('register/', upload_files, name='register'),
    path('check-duplicate/', check_duplicate, name='check_duplicate'),
    path('search/', search_scenarios, name='search'),
    path('home/', homepage, name='homepage'),
]

accountapp/models.py
from django.db import models

# Create your models here.

registerapp/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.db.models import JSONField


class Scenario(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='scenarios')
    file_name = models.CharField(max_length=100, unique=True)

    test_case_ids = JSONField()  # JSON 필드 사용
    usernames = JSONField()

    eADP = models.CharField(max_length=100)
    project_code = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    sw_version = models.CharField(max_length=100)
    weather = models.CharField(max_length=100)
    road_type = models.CharField(max_length=50)
    road_status = models.CharField(max_length=50)
    sun_status = models.CharField(max_length=50)
    test_mode = models.CharField(max_length=50)
    temperature = models.CharField(max_length=50)
    description = models.TextField(max_length=500)

    def __str__(self):
        return f"{self.file_name} - {self.project_code}"

accountapp/views.py
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy



class CustomLoginView(LoginView):
    template_name = 'accountapp/login.html'
    success_url = reverse_lazy('registerapp:homepage')

registerapp/views.py
import json, os
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST
from .models import Scenario
import logging

logger = logging.getLogger('django')

@login_required
@csrf_protect
def upload_files(request):
    logger.info("Upload files view called.")
    if request.method == 'GET':
        return render(request, 'registerapp/register.html')
    elif request.method == 'POST':
        logger.info("Processing POST request")
        files = request.FILES.getlist('files[]')
        base_folder = request.POST.get('base_folder', '')
        overwrite = json.loads(request.POST.get('overwrite', 'false'))

        file_paths = [generate_file_path(file.name, base_folder) for file in files]
        existing_files = [file_path for file_path in file_paths if os.path.exists(file_path)]
        new_files = [file for file, file_path in zip(files, file_paths) if file_path not in existing_files]

        if existing_files and not overwrite:
            return JsonResponse({
                'error': 'Duplicates detected',
                'duplicates': [os.path.basename(path) for path in existing_files]
            }, status=409)

        results = []
        for file, file_path in zip(files, file_paths):
            if file_path in existing_files and not overwrite:
                results.append({'status': 'error', 'message': 'File exists and overwrite not allowed',
                                'file': os.path.basename(file_path)})
            else:
                result = handle_uploaded_file(file, request.user, file_path, overwrite)
                results.append(result)

        return JsonResponse({
            'success': True,
            'uploaded_files': [result['file'] for result in results if result['status'] == 'success'],
            'errors': [result for result in results if result['status'] == 'error']
        })


def generate_file_path(filename, base_folder):
    base_path = "G:/공유 드라이브/010_ADUS/220_Development/910_Data/010_LoggingData/"
    folder = "999_Others"  # Default 폴더
    if 'eADP(eADM1)' in filename:
        folder = "101_eADP_eADM1"
    elif 'eADP(TCar)' in filename:
        folder = "100_eADP_TCar"
    elif 'ETC' in filename:
        folder = "200_Etc"

    complete_path = os.path.join(base_path, folder, base_folder, filename)
    logger.info(f"Generated file path: {complete_path}")
    return complete_path


def handle_uploaded_file(file, user, save_path, overwrite):
    try:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        if os.path.exists(save_path) and not overwrite:
            logger.warning(f"File already exists and overwrite not allowed: {file.name}")
            return {'status': 'error', 'message': f'File already exists and overwrite not allowed: {file.name}',
                    'file': file.name}

        with open(save_path, 'wb+') as destination:
            for chunk in file.chunks():
                destination.write(chunk)

        if file.name.endswith('.json'):
            with open(save_path, 'r', encoding='utf-8') as json_file:
                data = json.load(json_file)
                Scenario.objects.update_or_create(
                    file_name=file.name,
                    defaults={
                        'user': user,
                        'test_case_ids': data.get('Test_Case_IDs', []),
                        'usernames': data.get('usernames', []),
                        'eADP': data.get('eADP', ''),
                        'project_code': data.get('project_code', ''),
                        'location': data.get('location', ''),
                        'sw_version': data.get('sw_version', ''),
                        'weather': data.get('weather', ''),
                        'road_type': data.get('road_type', ''),
                        'road_status': data.get('road_status', ''),
                        'sun_status': data.get('sun_status', ''),
                        'test_mode': data.get('test_mode', ''),
                        'temperature': data.get('temperature', ''),
                        'description': data.get('description', '')
                    }
                )
        return {'status': 'success', 'message': f'File {file.name} uploaded successfully', 'file': file.name}
    except Exception as e:
        logger.exception("Failed to upload file")
        return {'status': 'error', 'message': str(e), 'file': file.name}

@require_POST
def check_duplicate(request):
    data = json.loads(request.body)
    file_path = data.get('filePath')
    is_duplicate = os.path.exists(file_path)
    return JsonResponse({'isDuplicate': is_duplicate})



def search_scenarios(request):
    query_params = {
        'test_case_id': request.GET.get('test_case_id', ''),
        'username': request.GET.get('username', ''),
        'eADP': request.GET.get('eADP', ''),
        'project_code': request.GET.get('project_code', ''),
        'location': request.GET.get('location', ''),
        'sw_version': request.GET.get('sw_version', ''),
        'weather': request.GET.get('weather', ''),
        'road_type': request.GET.get('road_type', ''),
        'road_status': request.GET.get('road_status', ''),
        'sun_status': request.GET.get('sun_status', ''),
        'test_mode': request.GET.get('test_mode', ''),
        'temperature': request.GET.get('temperature', ''),
        'user': request.GET.get('user', ''),
    }

    scenarios = Scenario.objects.all()
    for param, value in query_params.items():
        if value:
            if param == 'user':
                scenarios = scenarios.filter(user__username__icontains=value)
            else:
                scenarios = scenarios.filter(**{f'{param}__icontains': value})

    return render(request, 'registerapp/scenario_search.html', {'scenarios': scenarios})
@login_required
def homepage(request):
    return render(request, 'registerapp/home.html', {})

accountapp/templates/accountapp/account.html
{% extends 'base.html' %}

{% block content %}

    <div>
        <h1>testing</h1>
    </div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div style="text-align: center; margin: 4rem auto; display: flex; justify-content: center;">
    {% if user.is_authenticated %}
        <h1>(미정)</h1>
    {% else %}
     <div style="height: auto; width: 35rem; display: flex; flex-direction: column;
                 background-color: #FFFFFF; border-radius: 1rem; padding: 2rem;">

        <div>
            <h1>Login</h1>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" style="margin-left: auto; margin-right: auto;">
            </form>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

registerapp/templates/registerapp/home.html
{% extends 'base.html' %}

{% block content %}

<div style="display: flex; justify-content: center;">

    <div style="height: 100%; width: 50rem; background-color: #F7F7F7; border-radius: 1rem; margin: 3rem;">
        <div style="font-size: 20pt; margin: 2rem; display: flex; justify-content: center;">
          <h1>(미정)</h1>

        </div>

    </div>
</div>


{% endblock %}

registerapp/templates/registerapp/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<meta name="csrf-token" content="{{ csrf_token }}">

<div style="display: flex; justify-content: center; margin-top :5rem;">

    <div style="height: 40rem; width: 40rem; background-color: #FFFFFF; border-radius: 1rem; margin: 1rem; border: 1px solid #1E6988;">
        <div style="display: flex; justify-content: center; margin : 2rem;">
            <h1>Drop here!</h1>
        </div>

        <div style="display: flex; justify-content: center; margin : 2rem;">
            <div id="drop-box" class="drop-box"
                 style=" margin: 5rem;
                         display: flex; justify-content: center;
                         height: 20rem; width: 20rem;
                         border: 3px dashed #196CA1; border-radius: 3rem;
                         align-items: center;
                         color: #196CA1;
                         font-size: 50pt;">
                +
            </div>
        </div>
    </div>

    <div style="min-height: 40rem; width: 40rem; background-color: #FFFFFF; border-radius: 1rem; margin: 1rem; display: flex; flex-direction: column; justify-content: space-between; border: 1px solid #1E6988;">

        <div style="display: flex; justify-content: center; margin-top: 2rem;">
            <h1>Upload Files</h1>
        </div>
        <div id="message-container"
             style="display: flex; flex-direction: column; justify-content: space-between; flex-grow: 1;">
            <div id="message" style="font-size: 16pt; margin: 1rem; padding: 20px;"></div>

             <!-- 버튼 컨테이너 -->
        <div style="display: flex; justify-content: center; gap: 10px; margin: 2rem;">
            <button id="removeDuplicatesBtn" class="btn btn-warning"
                    style="flex-grow: 1; background-color: #FFC107; font-size: 15pt; color: black; display: none;">
                중복제거
            </button>
            <button id="overwriteBtn" class="btn btn-danger"
                    style="flex-grow: 1; background-color: #DC3545; font-size: 15pt; color: white; display: none;">
                덮어쓰기
            </button>
            <button id="uploadBtn" class="btn btn-info"
                    style="flex-grow: 1; background-color: #1E6988; font-size: 15pt; color: white; display: none;">
                Save
            </button>
        </div>

        </div>
    </div>

<!-- 파일 업로드 성공 모달 -->
    <div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="successModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="successModalLabel">파일 등록 성공</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>파일 등록이 잘 되었습니다.</p>
                    <ul id="uploadedFileList"></ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">확인</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/dragndrop.js' %}?v=1.01"> </script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body>
    {% include 'header.html' %}

    {% block content %}

    {% endblock %}

</body>
</html>

templates/head.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ADUS</title>

    <!--BOOTSTRAP LINK-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!--GOGGLE FONTS LINK-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
          rel="stylesheet">
    <!--DEFAULT CSS LINK-->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <!-- jQuery Standard Version -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!-- Popper.js for Bootstrap 4 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- Bootstrap 4 JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

</head>

templates/header.html
{% load static %}

<style>
    .header-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 10px;
        background-color: #F2F2F2;
        color: black;
        font-size: 20px;
    }

    .header-left, .header-right {
        display: flex;
        align-items: center;
        gap: 20px;

    .logo-container img {
        height: 100px;
        width: auto;
    }

    .user-info {
        display: flex;
        align-items: center;
        gap: 10px;
        font-size: 23px;
    }

    .menu-bar {
        display: flex;
        gap: 20px;
    }

    .dropdown {
        position: relative;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: white;
        min-width: 160px;
        box-shadow: 0 8px 16px rgba(0,0,0,0.2);
        z-index: 1;
    }

    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

    .dropdown-content a:hover { background-color: #F2F2F2; }

    .dropdown:hover .dropdown-content {
        display: block;
    }

    .dropdown:hover .dropbtn, .nav-link:hover {
        font-weight: bold;
    }

    .nav-link, .dropbtn {
        background: none;
        border: none;
        color: black;
        text-decoration: none;
        cursor: pointer;
    }

    .logout-button {
        background: none;
        border: none;
        color: black;
        cursor: pointer;
        text-decoration: underline;
    }

</style>

<div class="header-container">
    <div class="header-left">
        <div class="logo-container">
            <img src="{% static 'logo/adus_logo.png' %}">
        </div>
        {% if user.is_authenticated %}
        <div class="menu-bar">
            <div class="dropdown">
                <button class="dropbtn">|vDMS|</button>
                <div class="dropdown-content">
                    <a href="{% url 'registerapp:register' %}">|Register|</a>
                    <a href="{% url 'registerapp:search' %}">|Search|</a>
                </div>
            </div>
            <a href="{% url 'registerapp:homepage' %}" class="nav-link">|vFMS|</a>
        </div>
        {% endif %}
    </div>
    <div class="header-right">
        {% if user.is_authenticated %}
        <div class="user-info">
            <i class="fas fa-user-circle"></i>
            <span>{{ request.user }}</span>
        </div>
        <form action="{% url 'accountapp:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="logout-button">Logout</button>
        </form>
        {% endif %}
    </div>
</div>